Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-04, with the labels that each got.

#396 fix fleet deletion & drop dead code
  inc/fleet.class.php
  tests/suite-unit/PluginFlyvemdmFleet.php
Labels: bug, refactor

#397 Fix wrong user profile in enrollment
  inc/agent.class.php
  tests/suite-install/Config.php
  tests/suite-integration/PluginFlyvemdmAgent.php
Labels: bug

#399 Fix malformed MQTT messages when chagning topic layout
  install/upgrade/update_to_dev.php
Labels: bug, install

#400 Harmonize unapply method of Package deployment policy
  inc/policydeployapplication.class.php
Labels: refactor

#401 Allow recursion change for non default fleets
  inc/fleet.class.php
  tests/suite-unit/PluginFlyvemdmFleet.php
Labels: bug

#410 Certificate information on TLS step
  tpl/config-wizard.html.twig
Labels: documentation

#411 Drop useless method for unit tests
  tests/suite-unit/PluginFlyvemdmFleet.php
Labels: test

#416 Make code simpler
  inc/agent.class.php
Labels: refactor

#418 Fix tab number
  inc/config.class.php
  inc/menu.class.php
Labels: bug

#422 Fleet in the root entity should not be recursive
  install/installer.class.php
  tests/suite-install/Config.php
Labels: bug

#421 Update unit test for fleet
  tests/suite-unit/PluginFlyvemdmFleet.php
Labels: test

#423 Update the android app package id
  setup.php
Labels: bug

#428 Do not silently fail to update entity config
  inc/entityconfig.class.php
  tests/src/Glpi/Tests/CommonTestCase.php
  tests/suite-unit/PluginFlyvemdmEntityConfig.php
Labels: api, bug

#429 Mutualize helper method
  tests/src/Flyvemdm/Tests/CommonTestCase.php
  tests/suite-integration/PluginFlyvemdmAgent.php
  tests/suite-integration/PluginFlyvemdmFile.php
  tests/suite-integration/PluginFlyvemdmPackage.php
  tests/suite-integration/PluginFlyvemdmPolicyDeployFile.php
  tests/suite-integration/PluginFlyvemdmPolicyRemoveFile.php
  tests/suite-integration/PluginFlyvemdmTask.php
  tests/suite-unit/PluginFlyvemdmPolicyRemoveapplication.php
Labels: refactor

#434 Document type step
  inc/config.class.php
  tpl/config-wizard.html.twig
Labels: documentation

#437 Code refactor
  .travis.yml
  hook.php
  inc/menu.class.php
  inc/policydeployapplication.class.php
  inc/policydeployfile.class.php
  inc/policyinterface.class.php
  inc/policyremoveapplication.class.php
  inc/task.class.php
  tests/suite-integration/PluginFlyvemdmFile.php
  tests/suite-integration/PluginFlyvemdmPackage.php
  tests/suite-integration/PluginFlyvemdmPolicyDeployFile.php
Labels: refactor

#438 Add unit tests
  tests/suite-unit/PluginFlyvemdmEntityConfig.php
Labels: test

#440 Add missing search options
  inc/policy.class.php
Labels: bug

#431 Disable all sounds policy
  install/installer.class.php
  tests/suite-unit/PluginFlyvemdmAgent.php
Labels: feature

#442 Update locales
  .tx/config
  inc/notificationtargetinvitation.class.php
  locales/flyvemdm.pot
  locales/fr_FR.po
Labels: locales

#445 Locales update
  locales/fr_FR.mo
  locales/pt_BR.mo
  locales/ru.mo
Labels: locales

#446 Getting an agent by topic failed
  inc/agent.class.php
  tests/suite-integration/PluginFlyvemdmAgent.php
Labels: bug

#450 Support for spanish language
  locales/es_ES.po
  locales/es_MX.po
Labels: feature

#451 Invert build after_success sequence
  .travis.yml
Labels: ci

#453 Fix handling inventory
  inc/mqtthandler.class.php
Labels: bug

#454 Send informative notification for manual actions
  inc/agent.class.php
Labels: feature

#455 Remove check for external links
  ci/tets-jekyll.sh
Labels: build

#459 Follow branching of GLPI
  .travis.yml
  tests/before_script.sh
  tests/patches/fi-fix-obsolete-query.patch
  tests/patches/fi-raise-max-version.patch
Labels: ci

#460 FI patch ws incomplete
  setup.php
  tests/patches/fi-raise-max-version.patch
Labels: build, ci

#461 Some strings shall not be translated
  install/installer.class.php
Labels: bug

#458 Validate inventory XML
  inc/agent.class.php
  tests/suite-integration/PluginFlyvemdmAgent.php
Labels: feature, test

#462 Move policies to files per category
  install/installer.class.php
  install/policies/deployment.php
  install/policies/encryption.php
  install/policies/mdm.php
  install/policies/password.php
  install/policies/peripherals.php
  install/policies/phone.php
  install/policies/usb.php
  install/policies/userInterface.php
  tests/suite-install/Config.php
Labels: refactor
