Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-12, with the labels that each got.

#810 Fix twitter url
  _includes/contact/social.html
Labels: documentation

#808 Notification token in enrollment for FCM
  inc/agent.class.php
  install/mysql/plugin_flyvemdm_empty.sql
  install/upgrade_to_2_0.php
  tests/src/Flyvemdm/Tests/CommonTestCase.php
  tests/suite-integration/PluginFlyvemdmAgent.php
  tests/suite-integration/PluginFlyvemdmFleet.php
  tpl/_agentInfo.html.twig
  tpl/agent.html.twig
Labels: enrollment, feature

#811 Enrollment broken due to bad merge conflictr resolution
  inc/agent.class.php
Labels: bug

#815 Change graph types for dashboard
  inc/graph.class.php
Labels: refactor

#817 Wizard update
  inc/config.class.php
  tpl/config-wizard.html.twig
Labels: refactor

#822 Fix links in wizard
  tpl/config-wizard.html.twig
Labels: documentation

#832 Update plugin icon
  images/icon.png
  plugin.xml
Labels: refactor

#837 Fix content background
  css/codeDocumentation.css
  development/code-documentation/develop/resources/style.css
Labels: documentation

#850 History for packages and files
  inc/file.class.php
  inc/package.class.php
Labels: refactor

#851 Show some more info
  tpl/invitation.html.twig
Labels: feature

#854 MQTT subcribers tab only if the agent uses it
  inc/agent.class.php
Labels: refactor

#856 Add changes in CI for code documentation
  tests/after_success.sh
  tests/apidocs.sh
Labels: documentation
