Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-02, with the labels that each got.

#319 Make unit tests able to send backtrace on fatal errors
  tests/bootstrap.php
  tests/suite-integration/PluginFlyvemdmAgent.php
Labels: test

#311 Fix header display in coverage section
  _includes/head.html
  _layouts/coverage.html
  build/tests/coverage/assets/bootstrap.min.css
  css/report.css
Labels: documentation

#286 WIP New Contributing Guidelines Proposal
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
  images/footer.png
  images/header.png
Labels: documentation

#325 Re-add composer.lock
  composer.json
  composer.lock
Labels: build

#326 Fix coverage report styles
  .github/push_ghpages.sh
Labels: ci

#329 WIP Better guide for issue report and branching
  CONTRIBUTING.md
Labels: documentation

#310 Deleted invalid policies for Android
  install/installer.class.php
  install/upgrade/update_to_dev.php
  tests/suite-unit/PluginFlyvemdmAgent.php
Labels: bug

#330 Change index information
  index.html
Labels: documentation

#335 Fix inconsistencies in wizard
  tpl/config-wizard.html
Labels: bug

#336 Add information about app/bot that checks PR
  CONTRIBUTING.md
Labels: documentation

#346 Fix errors in punctuation
  CONTRIBUTING.md
Labels: documentation

#349 Update mqtt messages and topics
  _posts/static/2017-11-14-mqtt-messages-specifications.md
Labels: documentation

#354 Compatibility matrix
  README.md
Labels: documentation

#351 Fix for upgrade script
  install/upgrade/update_to_dev.php
Labels: bug
