Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-09, with the labels that each got.

#733 Fix upgrade
  install/install.class.php
Labels: bug

#735 Wrong dl_filename when updating a package
  inc/package.class.php
Labels: bug

#739 Fix dl filename
  inc/package.class.php
Labels: bug

#741 Demote official bit
  setup.php
Labels: build

#743 SystemD service
  scripts/flyvemdm.service
Labels: feature

#753 Add MQTT ports for backend
  inc/mqttclient.class.php
  install/install.class.php
  install/upgrade/update_to_dev.php
  tpl/config-messagequeue.html.twig
Labels: feature

#754 Add MQTT log tabs
  inc/agent.class.php
  inc/fleet.class.php
  inc/mqttlog.class.php
  inc/profile.class.php
  install/install.class.php
  install/upgrade_to_2.0.php
  tests/suite-integration/ProfileRight.php
  tests/suite-unit/PluginFlyvemdmMqttlog.php
  tpl/mqttlog_list.html.twig
Labels: feature

#756 Fix upgrade to develop process
  install/upgrade/update_to_dev.php
  install/upgrade_to_dev.php
Labels: bug

#766 Fix for transparent icon package
  inc/package.class.php
  tpl/package.html.twig
Labels: bug
