Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-11, with the labels that each got.

#763 Add some tests
  tests/suite-integration/PluginFlyvemdmProfile.php
  tests/suite-unit/PluginFlyvemdmProfile.php
Labels: test

#790 Restrict operator for boolean search options
  inc/agent.class.php
  inc/fleet.class.php
  inc/policy.class.php
  inc/wellknownpath.class.php
Labels: bug

#794 Remove whitespace
  inc/agent.class.php
Labels: style

#795 Improve status display
  inc/agent.class.php
Labels: bug

#796 Fix date log
  inc/mqtthandler.class.php
Labels: bug

#798 Give a pasword to the agent user account
  inc/agent.class.php
Labels: bug

#807 Change of input names
  front/agent.form.php
  inc/agent.class.php
  tests/suite-integration/PluginFlyvemdmAgent.php
Labels: refactor
