Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-03, with the labels that each got.

#359 Installation exception
  _posts/static/2018-02-01-installation-wizard.md
Labels: documentation

#357 Fix footer in coverage
  _includes/head.html
  css/coverage.css
Labels: documentation

#371 Git clone commands in installation article
  _posts/static/2018-02-01-installation-wizard.md
Labels: documentation

#372 Fix typo in wizard
  tpl/config-wizard.html.twig
Labels: documentation

#338 Workflow information
  _posts/static/2018-02-20-workflow.md
  _sass/_general.scss
  index.html
Labels: documentation

#375 Correct TLS step
  tpl/config-wizard.html.twig
Labels: documentation

#367 Fix deprecated GLPI methods calls
  inc/agent.class.php
  inc/config.class.php
  inc/fleet.class.php
  inc/invitation.class.php
  inc/mqtthandler.class.php
  inc/mqttuser.class.php
  inc/policy.class.php
  inc/wellknownpath.class.php
  install/installer.class.php
  setup.php
  tests/before_script.sh
  tests/patches/fi-master.patch
  tests/suite-integration/Entity.php
  tests/suite-integration/PluginFlyvemdmAgent.php
  tests/suite-integration/PluginFlyvemdmFile.php
  tests/suite-integration/PluginFlyvemdmFleet.php
  tests/suite-integration/PluginFlyvemdmInvitation.php
  tests/suite-integration/PluginFlyvemdmMqttuser.php
  tests/suite-integration/PluginFlyvemdmPackage.php
  tests/suite-integration/PluginFlyvemdmPolicyDeployFile.php
  tests/suite-integration/PluginFlyvemdmPolicyRemoveApplication.php
  tests/suite-integration/PluginFlyvemdmPolicyRemoveFile.php
  tests/suite-integration/PluginFlyvemdmTask.php
  tests/suite-unit/PluginFlyvemdmFile.php
  tests/suite-unit/PluginFlyvemdmPackage.php
Labels: bug

#369 Update code for better reading
  inc/policyboolean.class.php
  inc/policydeployapplication.class.php
  inc/policydeployfile.class.php
Labels: refactor

#363 Add menu to main itemtype displays
  front/agent.form.php
  front/agent.php
  front/config.form.php
  front/file.form.php
  front/file.php
  front/fleet.form.php
  front/fleet.php
  front/invitation.form.php
  front/invitation.php
  front/package.form.php
  front/package.php
  inc/menu.class.php
  tpl/menu.html.twig
Labels: feature

#358 Collect inventory data for debug
  inc/agent.class.php
  inc/config.class.php
  inc/package.class.php
  install/installer.class.php
  install/upgrade/update_to_dev.php
  setup.php
  tests/suite-integration/PluginFlyvemdmAgent.php
  tpl/config-debug.html.twig
Labels: enrollment, feature

#380 Simplify code
  inc/mqtthandler.class.php
Labels: refactor

#385 Fix manifest malfunction
  inc/mqtthandler.class.php
Labels: bug

#364 Send remove message to device
  inc/policybase.class.php
  inc/policydeployapplication.class.php
  inc/policyremoveapplication.class.php
  inc/task.class.php
  tests/suite-integration/PluginFlyvemdmPolicyRemoveApplication.php
  tests/suite-unit/PluginFlyvemdmPolicyRemoveapplication.php
Labels: test

#389 Use migration object to update configuration
  install/upgrade/update_to_dev.php
Labels: refactor

#390 Incomplete URL in qr code
  inc/invitation.class.php
  inc/notificationtargetinvitation.class.php
Labels: bug

#393 Hotfix for invitation token
  inc/notificationtargetinvitation.class.php
Labels: bug

#398 Show development revision in debug settings
  inc/config.class.php
  setup.php
  tpl/config-debug.html.twig
Labels: feature
