Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-07, with the labels that each got.

#574 WIP Update standard-version to version 4.4.0
  package.json
Labels: build

#582 Update locale translation
  locales/cs_CZ.po
  locales/es_ES.po
  locales/flyvemdm.pot
  locales/fr_FR.po
  locales/pt_BR.po
  locales/ru.po
Labels: locales

#586 New tests for Flyvemdm common class
  tests/suite-unit/PluginFlyvemdmCommon.php
Labels: test

#595 Improve general user interface
  inc/graph.class.php
  tpl/menu.html.twig
Labels: refactor

#594 Hide unused bug collector tool
  tpl/config-debug.html.twig
Labels: refactor

#596 Remove localization for strings which should not localized
  inc/entityconfig.class.php
  tpl/config-wizard.html.twig
Labels: bug, locales

#542 Render policy value with Twig
  css/style.css
  inc/policybase.class.php
  inc/policyboolean.class.php
  inc/policydeployapplication.class.php
  inc/policydeployfile.class.php
  inc/policydropdown.class.php
  tests/suite-unit/PluginFlyvemdmPolicyBase.php
  tpl/fleet_policy.html.twig
  tpl/policy_value.html.twig
Labels: refactor

#597 Fix description for mdm types
  inc/agent.class.php
Labels: bug

#599 Update build matrix
  .travis.yml
  tests/after_success.sh
  tests/update_locales.sh
Labels: build, ci

#600 Update README.md
  README.md
Labels: documentation

#580 Add new task status
  inc/policybase.class.php
  tests/suite-unit/PluginFlyvemdmPolicyBase.php
Labels: feature

#603 Update style following the UWP guidelines
  _sass/_index.scss
  contact.html
  images/contact1.jpg
Labels: refactor, style

#605 Update project site's style
  _sass/_index.scss
  development/devdocs/index.html
  howtos/index.html
  news.html
  projects.html
Labels: documentation

#608 Update project site's style
  _includes/header.html
  _layouts/container2.html
  _sass/_index.scss
  contact.html
Labels: documentation

#607 Add tests for tasks
  inc/task.class.php
  tests/suite-unit/PluginFlyvemdmTask.php
Labels: test

#609 Refactor code for keep or change session on tests
  tests/before_script.sh
  tests/src/Flyvemdm/Tests/CommonTestCase.php
  tests/src/Glpi/Tests/CommonTestCase.php
  tests/suite-integration/PluginFlyvemdmAgent.php
  tests/suite-integration/PluginFlyvemdmFleet.php
  tests/suite-unit/PluginFlyvemdmAgent.php
Labels: test

#611 Update responsive web design
  _sass/_index.scss
Labels: documentation

#614 Fix message of FusionInventory agent not created
  inc/agent.class.php
Labels: bug

#617 Adaptate to responsive web design
  _sass/_general.scss
  _sass/_index.scss
Labels: documentation

#618 Fix for plugin upgrade
  setup.php
Labels: bug

#622 Script update for publishing changes to gh-pages
  tests/after_success.sh
Labels: ci

#625 Add db scheme
  _includes/header.html
  development/DB-scheme/index.html
  images/db-scheme.png
Labels: documentation

#627 Delete removed reports on CI
  tests/after_success.sh
Labels: ci

#628 Patch for deletion of old coverage report
  tests/after_success.sh
Labels: ci

#624 Update style following the UWP guidelines
  _includes/header.html
  _layouts/container.html
  _sass/_general.scss
  _sass/_index.scss
  development/devdocs/index.html
  howtos/index.html
  images/business.jpg
  images/business2.jpg
  images/business3.jpg
  images/code-doc.jpg
  images/email-3.svg
  images/home-3.svg
  images/how-to.jpg
Labels: refactor, style

#629 Create archive with dependencies (vendor/ folder)
  RoboFile.php
  composer.json
  composer.lock
Labels: build

#630 Bump version to 2.0.0-rc.2
  setup.php
Labels: build

#665 Add formGenerator test
  tests/suite-unit/PluginFlyvemdmPolicyBase.php
Labels: test

#671 New tests for Taks class
  tests/suite-unit/PluginFlyvemdmTask.php
Labels: refactor, test
