Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-05, with the labels that each got.

#465 Better column name and allow view of invitations
  inc/invitation.class.php
Labels: bug

#468 Enhnance again UI
  inc/invitation.class.php
  install/installer.class.php
  install/mysql/plugin_flyvemdm_empty.sql
  install/upgrade/update_to_dev.php
Labels: feature

#469 A policy has a wrong category
  install/policies/mdm.php
  install/policies/peripherals.php
Labels: bug

#471 Hotfix for install script
  install/upgrade/update_to_dev.php
Labels: bug

#476 Quick fix for issue template format
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: bug

#477 Patch for CI problems with FI master branch
  tests/before_script.sh
  tests/patches/fi-master-search-options.patch
Labels: ci

#482 Fix line endings of templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: documentation

#486 Include policies files in locales extraction
  RoboFile.php
Labels: bug, build

#483 Policy for unknown sources
  install/policies/phone.php
  tests/suite-install/Config.php
  tests/suite-unit/PluginFlyvemdmAgent.php
Labels: feature

#487 Fix message not sent on cascaded creation of task
  inc/mqtthandler.class.php
  inc/policydeployapplication.class.php
  inc/policydeployfile.class.php
Labels: bug

#490 Move and reverse unknown sources policy
  install/policies/deployment.php
  install/policies/phone.php
Labels: bug

#500 Add professional services
  README.md
Labels: documentation

#504 Fix warning with PHP 7.2
  tools/cli_install.php
Labels: bug

#506 Show whether a fleet is managed or not
  inc/fleet.class.php
  tpl/fleet.html.twig
Labels: feature

#510 Cleanup attempt
  tests/bootstrap.php
  tests/src/Glpi/Tests/CommonTestCase.php
  tests/suite-install/Config.php
Labels: refactor, test

#512 Migration update
  install/upgrade/update_to_dev.php
Labels: bug

#518 Add new rules to disable for FI configuration in Wizard
  tpl/config-wizard.html.twig
Labels: documentation

#519 Remove FI patch for CI
  tests/before_script.sh
  tests/patches/fi-master-search-options.patch
Labels: ci

#515 New fields to display on search
  inc/task.class.php
Labels: refactor

#522 Invitation text update
  install/installer.class.php
  locales/pt_BR.po
  locales/ru.po
Labels: bug

#509 Add min and max version of OS for policies
  inc/policy.class.php
  install/mysql/plugin_flyvemdm_empty.sql
  install/policies/deployment.php
  install/policies/encryption.php
  install/policies/mdm.php
  install/policies/password.php
  install/policies/peripherals.php
  install/policies/phone.php
  install/policies/usb.php
  install/policies/userInterface.php
  install/upgrade/update_to_dev.php
Labels: feature

#526 Enhance dropdown when applying policies
  inc/policy.class.php
  inc/task.class.php
Labels: feature

#530 Fix paging
  tpl/agent_fleet.html.twig
Labels: bug

#533 Patch for upgrade installation
  install/upgrade/update_to_dev.php
Labels: bug, install

#537 Policies dropdown on GLPI UI
  inc/policy.class.php
  inc/task.class.php
Labels: bug

#501 WIP Update style following the UWP guidelines
  404.html
  Gemfile
  Gemfile.lock
  _config.yml
  _includes/footer.html
  _layouts/code-documentation.html
  _posts/2017-11-30-flyve-mdm-plugin-for-glpi.md
  _posts/code-documentation/2017-11-16-Agent.md
  _posts/static/2017-11-14-use-cases.md
  _sass/_index.scss
  contact.html
  css/main.scss
  development/devdocs/index.html
  images/Telegram.svg
  images/Twitter.svg
  images/Twitter2.png
  images/Twitter2.svg
  images/easy-icon.svg
  images/logo3.png
  images/mobile-icon.svg
  images/security-icon.svg
  index.html
  news.html
Labels: refactor

#539 Fix for default value of audo profile
  install/policies/userInterface.php
Labels: bug
