Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-08, with the labels that each got.

#673 Add unit test for Tasks
  tests/suite-unit/PluginFlyvemdmTask.php
Labels: test

#666 Responsive web design
  _sass/_index.scss
Labels: documentation

#685 Fix allowed failures
  .travis.yml
Labels: build, ci

#680 Test avoid duplicate string
  tests/suite-install/Config.php
Labels: test

#615 Compatibiliy with GLPI 9.4
  inc/agent.class.php
  inc/entityconfig.class.php
  inc/file.class.php
  inc/fleet.class.php
  inc/geolocation.class.php
  inc/invitation.class.php
  inc/invitationlog.class.php
  inc/package.class.php
  inc/policy.class.php
  inc/policycategory.class.php
  inc/task.class.php
  inc/taskstatus.class.php
  inc/wellknownpath.class.php
Labels: feature

#691 Errors in composer
  composer.json
Labels: bug, build

#690 Task and Taskstatus data for tests
  tests/src/Flyvemdm/Tests/CommonTestCase.php
Labels: test

#695 Fix upgrade
  install/install.class.php
Labels: bug, install

#565 Add tests to taskstatus
  tests/src/Flyvemdm/Tests/CommonTestCase.php
  tests/suite-unit/PluginFlyvemdmTaskstatus.php
Labels: test

#697 Fix typo DBMD to DBMS
  tpl/config-wizard.html.twig
Labels: documentation

#688 Change for coverage report
  .atoum.php
  tests/after_success.sh
Labels: ci, dependent, documentation

#699 Warnings when running manually parsePackage
  inc/package.class.php
Labels: bug

#707 Dropdown shall not show empty categories
  inc/policy.class.php
Labels: bug

#701 Protect policies test with a policy
  install/policies/mdm.php
  tests/src/Flyvemdm/Tests/CommonTestCase.php
Labels: feature, policy

#681 Responsive web design
  _sass/_index.scss
Labels: documentation

#709 Update readme content
  README.md
Labels: documentation

#711 Hot fix for generate code coverge
  tests/after_success.sh
Labels: documentation

#713 Script for publishing code documentation
  .travis.yml
  tests/after_success.sh
  tests/apidocs.sh
Labels: documentation

#708 Add (basic) periodic geolocation
  install/policies/mdm.php
  tests/src/Flyvemdm/Tests/CommonTestCase.php
Labels: feature

#715 Remove support for GLPI 9.2
  .travis.yml
  inc/agent.class.php
  inc/invitation.class.php
  install/installer.class.php
  setup.php
  tests/src/Glpi/Tests/CommonTestCase.php
Labels: feature

#716 Fix ci script for update gh-pages
  tests/after_success.sh
  tests/apidocs.sh
Labels: ci, documentation

#719 Tests refactor
  tests/suite-install/Config.php
  tests/suite-integration/Entity.php
  tests/suite-integration/PluginFlyvemdmAgent.php
  tests/suite-integration/PluginFlyvemdmMqttuser.php
  tests/suite-integration/ProfileRight.php
  tests/suite-uninstall/Config.php
  tests/suite-unit/PluginFlyvemdmAgent.php
  tests/suite-unit/PluginFlyvemdmCommon.php
  tests/suite-unit/PluginFlyvemdmEntityConfig.php
  tests/suite-unit/PluginFlyvemdmFleet.php
  tests/suite-unit/PluginFlyvemdmFusionInventory.php
  tests/suite-unit/PluginFlyvemdmPolicyBoolean.php
  tests/suite-unit/PluginFlyvemdmPolicyDeployapplication.php
  tests/suite-unit/PluginFlyvemdmPolicyDeployfile.php
  tests/suite-unit/PluginFlyvemdmPolicyDropdown.php
  tests/suite-unit/PluginFlyvemdmPolicyInteger.php
  tests/suite-unit/PluginFlyvemdmPolicyRemoveapplication.php
  tests/suite-unit/PluginFlyvemdmPolicyString.php
  tests/suite-unit/PluginFlyvemdmTask.php
Labels: refactor

#728 backport compatibility with GLPI 9.4
  inc/agent.class.php
  inc/entityconfig.class.php
  inc/file.class.php
  inc/fleet.class.php
  inc/geolocation.class.php
  inc/invitation.class.php
  inc/invitationlog.class.php
  inc/package.class.php
  inc/policy.class.php
  inc/policycategory.class.php
  inc/task.class.php
  inc/taskstatus.class.php
  inc/wellknownpath.class.php
Labels: bug
