Repository flyve-mdm/glpi-plugin, pull requests merged in 2018-06, with the labels that each got.

#541 Fix for marks on geolocation map
  tpl/computer_geolocation.html.twig
Labels: bug

#548 Dashboard os version graph
  inc/graph.class.php
  tpl/menu.html.twig
Labels: bug

#534 Fix agent and fleet notification on upgrade
  install/upgrade/update_to_dev.php
Labels: bug, install

#549 Debug inventory file before enrol
  inc/agent.class.php
  inc/common.class.php
  tests/suite-integration/PluginFlyvemdmAgent.php
  tests/suite-unit/PluginFlyvemdmCommon.php
Labels: refactor

#551 Type of is_online is specific
  inc/agent.class.php
Labels: bug

#557 Update for vendors
  composer.lock
Labels: build

#560 WIP Fix labels repeated
  inc/graph.class.php
Labels: bug

#561 WIP Change datetime format in request
  tpl/computer_geolocation.html.twig
Labels: bug

#575 Add some refinements
  CONTRIBUTING.md
Labels: documentation

#570 Update project site's style
  index.html
Labels: documentation
